# Generated by Django 4.2.11 on 2024-04-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='cachorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='dogia_app.cachorro'),
        ),
    ]
