# Generated by Django 4.2.11 on 2024-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0002_alter_imagem_cachorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
