# Generated by Django 4.2.11 on 2024-04-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0002_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
