# Generated by Django 4.2.11 on 2024-04-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0003_alter_cachorro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
