# Generated by Django 4.2.11 on 2024-04-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0003_alter_raca_data_criacao_alter_usuario_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='data_alteracao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_alteracao',
            field=models.DateTimeField(null=True),
        ),
    ]
