# Generated by Django 4.2.11 on 2024-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0004_alter_cachorro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
