# Generated by Django 4.2.11 on 2024-04-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0004_raca_data_alteracao_usuario_data_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='data_alteracao',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_alteracao',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
