# Generated by Django 4.2.11 on 2024-04-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0005_alter_raca_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
