# Generated by Django 4.2.11 on 2024-04-06 03:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0006_alter_raca_data_alteracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.SmallIntegerField(choices=[(1, 'Macho'), (2, 'Fêmea')])),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('status', models.BooleanField(default=True)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Buscado'), (2, 'Avistado')], default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raca', to='dogia_app.raca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='dogia_app.usuario')),
            ],
        ),
    ]
