# Generated by Django 4.2.11 on 2024-04-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0007_cachorro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('cachorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cachorro', to='dogia_app.cachorro')),
            ],
        ),
    ]
