# Generated by Django 4.2.11 on 2024-04-07 16:15

import django.contrib.postgres.fields
from django.db import migrations, models
import dogia_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0008_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachorro',
            name='embedding',
        ),
        migrations.AddField(
            model_name='imagem',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='caminho',
            field=models.ImageField(upload_to=dogia_app.models.generate_filename),
        ),
    ]
