# Generated by Django 4.2.11 on 2024-04-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0009_remove_cachorro_embedding_imagem_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('id_avistado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistado', to='dogia_app.cachorro')),
                ('id_buscado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscado', to='dogia_app.cachorro')),
            ],
        ),
    ]
