# Generated by Django 4.2.13 on 2024-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0009_usuarioavista_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='raca_certeza',
            field=models.FloatField(default=0),
        ),
    ]
