# Generated by Django 4.2.11 on 2024-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0010_combinacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacao',
            name='distancia',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
