# Generated by Django 4.2.13 on 2024-06-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0011_alter_cachorro_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raca', to='dogia_app.raca'),
        ),
    ]
