# Generated by Django 4.2.11 on 2024-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0011_combinacao_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
