# Generated by Django 4.2.11 on 2024-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0012_alter_cachorro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacao',
            name='distancia_bruta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combinacao',
            name='score_bruto',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
