# Generated by Django 4.2.13 on 2024-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogia_app', '0012_alter_cachorro_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='raca_certeza',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
